{
  "name": "<%= packageName %>",
  "description": "<%= itemNameCapitalCase %>",
  "private": true,
  "version": "0.0.1",
  "scripts": {
    "build-storybook": "storybook build",
    "build": "tsc && vite build",
    "clean": "rimraf .turbo node_modules dist coverage",
    "dev": "vite",
    "format": "prettier --list-different '**/*.{js,jsx,ts,tsx,json,md}'",
    "format:fix": "npm run format -- --write",
    "lint": "eslint '**/*.{js,jsx,ts,tsx}'",
    "lint:fix": "npm run lint -- --fix",
    "preview": "vite preview",
    "storybook": "storybook dev -p 6006",
    "test": "jest"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.16.0"
  },
  "devDependencies": {
    "@storybook/addon-a11y": "^7.4.6",
    "@storybook/addon-essentials": "^7.4.6",
    "@storybook/addon-interactions": "^7.4.6",
    "@storybook/addon-links": "^7.4.6",
    "@storybook/addon-onboarding": "^1.0.8",
    "@storybook/blocks": "^7.4.6",
    "@storybook/react": "^7.4.6",
    "@storybook/react-vite": "^7.4.6",
    "@storybook/theming": "^7.4.6",
    "@storybook/testing-library": "^0.2.2",
    "@testing-library/dom": "^9.3.3",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.5.1",
    "@types/jest": "^29.5.5",
    "@types/node": "^20.8.5",
    "@types/react": "^18.2.28",
    "@types/react-dom": "^18.2.13",
    "@vitejs/plugin-react": "^4.1.0",
    "eslint": "^8.51.0",
    "eslint-config-custom": "*",
    "eslint-plugin-storybook": "^0.6.15",
    "jest": "^29.7.0",
    "jest-config-custom": "*",
    "jest-environment-jsdom": "^29.7.0",
    "msw": "1.3.2",
    "storybook": "^7.4.6",
    "storybook-dark-mode": "^3.0.1",
    "ts-jest": "^29.1.1",
    "typescript": "^5.2.2",
    "vite": "^4.4.11",
    "vite-tsconfig-paths": "^4.2.1"
  },
  "msw": {
    "workerDirectory": "public"
  }
}
