{
  "name": "<%= packageName %>",
  "description": "<%= itemNameCapitalCase %>",
  "private": true,
  "version": "0.0.1",
  "scripts": {
    "build": "next build",
    "clean": "rimraf .turbo node_modules build coverage .next out",
    "dev": "next dev --port 3000",
    "format": "prettier --list-different '**/*.{js,jsx,ts,tsx,json,md}'",
    "format:fix": "npm run format -- --write",
    "lint": "next lint",
    "lint:fix": "npm run lint -- --fix",
    "start": "next start",
    "test": "jest"
  },
  "dependencies": {
    "next": "^14.1.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@code-shaper/eslint-config": "^1.*",
    "@code-shaper/jest-config": "^1.*",
    "@storybook/addon-a11y": "^7.6.17",
    "@storybook/addon-docs": "^7.6.17",
    "@storybook/addon-essentials": "^7.6.17",
    "@storybook/addon-interactions": "^7.6.17",
    "@storybook/addon-links": "^7.6.17",
    "@storybook/blocks": "^7.6.17",
    "@storybook/nextjs": "^7.6.17",
    "@storybook/react": "^7.6.17",
    "@storybook/theming": "^7.6.17",
    "@testing-library/dom": "^9.3.4",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^14.2.2",
    "@testing-library/user-event": "^14.5.2",
    "@types/jest": "^29.5.12",
    "@types/node": "^20.12.4",
    "@types/react": "^18.2.74",
    "@types/react-dom": "^18.2.24",
    "eslint": "^8.57.0",
    "eslint-config-next": "13.5.6",
    "eslint-plugin-storybook": "^0.8.0",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "storybook": "^7.6.17",
    "storybook-dark-mode": "^3.0.3",
    "ts-jest": "^29.1.2",
    "typescript": "^5.4.4"
  }
}
